variables:
  projectVersion: 1
  configuration: Release
  solution: UKHO.Logging.EventHubLogProvider.sln
  progetFeed: https://proget.ukho.gov.uk/nuget/ukho.trusted/
  pipelineName: $(BuildDefinitionName)_$(projectVersion).$(date:yy)$(DayOfYear)$(rev:.r)
  
name: $(BuildDefinitionName)_$(projectVersion).$(date:yy)$(DayOfYear)$(rev:.r)

trigger: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      name: NautilusBuild
    workspace:
      clean: all
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 6.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet restore
      displayName: Restore Packages

    - powershell: ./Apply-AssemblyVersionAndDefaults.ps1 -buildNumber $(Build.BuildNumber) -solutionDirectory $(Build.SourcesDirectory)
      displayName: Apply Version Number

    - script: dotnet build $(solution) -c $(configuration) --no-restore
      displayName: Build Project

    - script: dotnet test $(solution) --no-build -c $(configuration) --logger:"trx;LogFileName=$(Agent.BuildDirectory)/TestResults/$(pipelineName).trx"
      displayName: Test Project

    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testRunner: VSTest
        testResultsFiles: '$(Agent.BuildDirectory)/TestResults/*.trx'
        failTaskOnFailedTests: true
        mergeTestResults: true

    - script: dotnet pack $(solution) --no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)
      displayName: Pack Project

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Atrifact
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifact: $(Build.DefinitionName)
  
- stage: Proget
  jobs:
  - deployment: Publish_To_ProGet
    displayName: Publish To ProGet
    pool:
      name: NautilusRelease
    environment: EventHubLogProvider-ProGet
    strategy:
      runOnce:
        deploy:
          steps:
          - powershell: dotnet nuget push "$(Pipeline.Workspace)/**/$("$(Build.BuildNumber)".replace('_','.')).nupkg" -k $(progetApiKey) -s $(progetFeed)
            env:
              progetApiKey : $(progetApiKey)
            displayName: Publish Package
            
- stage: Nuget
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
    - deployment: Publish_To_NuGet
      displayName: Publish To NuGet
      pool:
        name: NautilusRelease
      environment: EventHubLogProvider-NuGet
      strategy:
        runOnce:
          deploy:
            steps:
            - powershell: dotnet nuget push "$(Pipeline.Workspace)/**/$("$(Build.BuildNumber)".replace('_','.')).nupkg" -k $(nugetApiKey) -s https://api.nuget.org/v3/index.json --no-symbols true
              env:
                nugetApiKey : $(nugetApiKey)
              displayName: Publish Package
