variables:
  projectVersion: 1
  configuration: Release
  solution: UKHO.Logging.EventHubLogProvider.sln
  
name: $(BuildDefinitionName)_$(projectVersion).$(date:yy)$(DayOfYear)$(rev:.r)

pr:
  - master

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      name: NautilusBuild
    workspace:
      clean: all
    steps:
    - script: dotnet restore
      displayName: Restore Packages

    - powershell: ./Apply-AssemblyVersionAndDefaults.ps1 -buildNumber $(Build.BuildNumber) -solutionDirectory $(Build.SourcesDirectory)
      displayName: Apply Version Number

    - script: dotnet build $(solution) -c $(configuration) --no-restore
      displayName: Build Project

    - script: dotnet test $(solution) --no-build -c $(configuration) --logger:trx -r $(Agent.BuildDirectory)/TestResults 
      displayName: Test Project

    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '$(Agent.BuildDirectory)/TestResults/*.trx'
        failTaskOnFailedTests: true
        mergeTestResults: true

    # TODO - Index Symbols?

    - script: dotnet pack $(solution) --no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)
      displayName: Pack Project

    - task: PublishPipelineArtifact@1
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifact: $(Build.DefinitionName)
  
- stage: deploy
  jobs:
  - deployment: publish
    displayName: publish package
    pool:
      name: NautilusRelease
    environment: live
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo $(Pipeline.Workspace)





