variables:
  ProjectVersion: 1
  Configuration: Release

name: $(BuildDefinitionName)_$(ProjectVersion).$(date:yy)$(DayOfYear)$(rev:.r)

pr:
  - master

pool:
  name: 'NautilusBuild'

steps:
- script: dotnet restore
  displayName: Restore Packages

- powershell: ./Apply-AssemblyVersionAndDefaults.ps1 -buildNumber $(Build.BuildNumber) -solutionDirectory $(Build.SourcesDirectory)
  displayName: Apply Version Number

- script: dotnet build UKHO.Logging.EventHubLogProvider.sln -c $(Configuration) --no-restore
  displayName: Build Project

- script: dotnet test --no-build -c $(Configuration) --logger:trx -r $(Agent.BuildDirectory)/TestResults 
  displayName: Test Project
