variables:
  projectVersion: 1
  configuration: Release
  solution: UKHO.Logging.EventHubLogProvider.sln
  progetFeed: https://progetcloud.ukho.gov.uk/nuget/ukho.trusted/v3/index.json
  
name: $(Build.DefinitionName)_$(projectVersion).$(date:yy)$(DayOfYear)$(rev:.r)

trigger: none

stages:
- stage: checks
  displayName: 'Checks'
  jobs:
  - job: snyk
    displayName: 'Run Snyk security scans'
    pool:
      name: NautilusBuild
    workspace:
      clean: all
    steps:
      - checkout: self
        displayName: 'Checkout repository (ensure global.json present)'
        
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          useGlobalJson: true

      - task: DotNetCoreCLI@2
        displayName: ".Net Core - NuGet restore non-test projects"
        inputs:
          command: restore
          projects: |
            **/*.csproj
            !**/*Tests.csproj
          restoreArguments: '-property:Configuration=$(configuration)'
          feedsToUse: config
          noCache: true
          nugetConfigPath: '$(Build.SourcesDirectory)\nuget.config'
          workingDirectory: '$(Build.SourcesDirectory)'
          packagesDirectory: '$(Build.SourcesDirectory)\packages'

      - task: UkhoSnykScanTask@0
        displayName: 'Snyk SAST scan'
        condition: succeededOrFailed()
        inputs:
          failOnIssues: true # Fails if any issues are found
          organization: observability-LS52jXuMTiWp8zh4KuRtea
          serviceConnectionEndpoint: "Snyk - Observability"
          testType: code
          monitorWhen: never
          codeSeverityThreshold: medium

      - task: UkhoSnykScanTask@0
        displayName: 'Snyk SCA scan'
        condition: succeededOrFailed()
        inputs:
          failOnIssues: true # Fails if any issues are found
          organization: observability-LS52jXuMTiWp8zh4KuRtea
          serviceConnectionEndpoint: "Snyk - Observability"
          testType: app
          monitorWhen: never
          severityThreshold: medium
          additionalArguments: --all-projects

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Snyk scan results'
        condition: succeededOrFailed()
        inputs:
          targetPath: '$(Agent.TempDirectory)' 
          artifact: Snyk_Scan
          publishLocation: 'pipeline'

- stage: build
  displayName: "Build"
  jobs:
  - job: run_build
    displayName: "Run build"
    pool:
      name: NautilusBuild
    workspace:
      clean: all
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 10.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet restore
      displayName: Restore Packages

    - powershell: ./Apply-AssemblyVersionAndDefaults.ps1 -buildNumber $(Build.BuildNumber) -solutionDirectory $(Build.SourcesDirectory)
      displayName: Apply Version Number

    - script: dotnet build $(solution) -c $(configuration) --no-restore
      displayName: Build Project

    - script: dotnet test $(solution) --no-build -c $(configuration) --logger:trx --results-directory $(Agent.BuildDirectory)/TestResults
      displayName: Test Project

    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testRunner: VSTest
        testResultsFiles: '$(Agent.BuildDirectory)/TestResults/*.trx'
        failTaskOnFailedTests: true
        mergeTestResults: true

    - script: dotnet pack $(solution) --no-build -c $(configuration) -o $(Build.ArtifactStagingDirectory)
      displayName: Pack Project

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Atrifact
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifact: $(Build.DefinitionName)
  
- stage: proget
  displayName: "Publish to ProGet"
  dependsOn:
    - "build"
    - "checks"
  jobs:
  - deployment: Publish_To_ProGetCloud
    displayName: 'Publish To ProGet Cloud'
    condition: succeeded()
    pool:
      name: NautilusRelease
    environment: EventHubLogProvider-ProGet
    strategy:
      runOnce:
        deploy:
          steps:
          - pwsh: dotnet nuget push "$(Pipeline.Workspace)/**/$("$(Build.BuildNumber)".replace('_','.')).nupkg" -k $(progetApiKey) -s $(progetFeed)
            env:
              progetApiKey : $(progetApiKey)
            displayName: Publish Package
            
- stage: nuget
  displayName: "Publish to Nuget"
  dependsOn:
    - "build"
    - "checks"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    - group: nuget-deployment-vars
  jobs:
    - deployment: Publish_To_NuGet
      displayName: Publish To NuGet
      pool:
        name: NautilusRelease
      environment: EventHubLogProvider-NuGet
      strategy:
        runOnce:
          deploy:
            steps:
            - pwsh: dotnet nuget push "$(Pipeline.Workspace)/**/$("$(Build.BuildNumber)".replace('_','.')).nupkg" -k $(nugetApiKey) -s https://api.nuget.org/v3/index.json --no-symbols
              env:
                nugetApiKey : $(nugetApiKey)
              displayName: Publish Package
